In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("GPAs_part_1.csv")

In [3]:
df

,Unnamed: 0,postid,Name,ExtractName,Address,Year,GPA400,GPA375,GPA350,GPA325,GPA300,GPA250,GPA200,GPA100,GPA000
0,0,10011,American University,American University,"4400 Massachusetts Avenue, NW, Washington, Dis...",2023-2024,15%,25%,30%,20%,7%,2%,1%,0%,0%
1,1,10011,American University,American University,"4400 Massachusetts Avenue, NW, Washington, D.C...",2021-2022,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%
2,2,10011,American University,Western New England University,"1215 Wilbraham Road, Springfield, MA, 01119",2023-2024,36.43%,10.69%,12.66%,12.10%,11.11%,11.95%,4.92%,0.14%,0.00%
3,3,10011,American University,Loyola University Maryland,"4501 North Charles Street, Baltimore, MD, 2121...",2023-2024,33%,23%,21%,11%,6%,5%,1%,0%,0%
4,4,10012,Clark University,Clark University,"950 Main Street, Worcester, Massachusetts, 016...",2023-2024,31%,24%,21%,13%,7%,4%,0%,0%,0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,623,34274,Wayne State University,Wayne State University,"42 W. Warren Ave., Detroit, MI. 48202",2020-2021,12.87%,19.34%,18.49%,14.99%,13.45%,16.74%,4.04%,0.07%,NaN
624,624,34274,Wayne State University,Stanford University,"450 Jane Stanford Way, Stanford, CA 94305",2023-2024,75.2%,15.5%,5.8%,2.9%,0.7%,NaN,NaN,NaN,NaN
625,625,34276,Utah State University,University of Utah,"201 Presidents Circle, Salt Lake City, Utah, 8...",2023-2024,11.0%,39.0%,24.0%,17.0%,7.0%,2.0%,0.0%,0.0%,0.0%
626,626,34276,Utah State University,Unknown University,Unknown Address,2023-2024,11.0%,39.0%,24.0%,17.0%,7.0%,2.0%,0.0%,0.0%,0.0%
627,627,34276,Utah State University,Mount Marty University,"1105 W 8th Street, Yankton, SD 57078",2023-2024,13%,22%,30%,13%,10%,11%,1%,0%,0%

In [6]:
df=df.drop(columns=['Unnamed: 0'])

In [7]:
df

,postid,Name,ExtractName,Address,Year,GPA400,GPA375,GPA350,GPA325,GPA300,GPA250,GPA200,GPA100,GPA000
0,10011,American University,American University,"4400 Massachusetts Avenue, NW, Washington, Dis...",2023-2024,15%,25%,30%,20%,7%,2%,1%,0%,0%
1,10011,American University,American University,"4400 Massachusetts Avenue, NW, Washington, D.C...",2021-2022,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%
2,10011,American University,Western New England University,"1215 Wilbraham Road, Springfield, MA, 01119",2023-2024,36.43%,10.69%,12.66%,12.10%,11.11%,11.95%,4.92%,0.14%,0.00%
3,10011,American University,Loyola University Maryland,"4501 North Charles Street, Baltimore, MD, 2121...",2023-2024,33%,23%,21%,11%,6%,5%,1%,0%,0%
4,10012,Clark University,Clark University,"950 Main Street, Worcester, Massachusetts, 016...",2023-2024,31%,24%,21%,13%,7%,4%,0%,0%,0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,34274,Wayne State University,Wayne State University,"42 W. Warren Ave., Detroit, MI. 48202",2020-2021,12.87%,19.34%,18.49%,14.99%,13.45%,16.74%,4.04%,0.07%,NaN
624,34274,Wayne State University,Stanford University,"450 Jane Stanford Way, Stanford, CA 94305",2023-2024,75.2%,15.5%,5.8%,2.9%,0.7%,NaN,NaN,NaN,NaN
625,34276,Utah State University,University of Utah,"201 Presidents Circle, Salt Lake City, Utah, 8...",2023-2024,11.0%,39.0%,24.0%,17.0%,7.0%,2.0%,0.0%,0.0%,0.0%
626,34276,Utah State University,Unknown University,Unknown Address,2023-2024,11.0%,39.0%,24.0%,17.0%,7.0%,2.0%,0.0%,0.0%,0.0%
627,34276,Utah State University,Mount Marty University,"1105 W 8th Street, Yankton, SD 57078",2023-2024,13%,22%,30%,13%,10%,11%,1%,0%,0%

In [9]:
df_same=df[df['Name']==df['ExtractName']]

In [30]:
df_same=df_same.drop(df_same[df_same['GPA400']=='0'].index)

In [38]:
df_same=df_same.drop(df_same[(df_same['GPA400']=="0%") & (df_same['GPA375']=="0%")& (df_same['GPA350']=="0%")& (df_same['GPA325']=="0%")& (df_same['GPA300']=="0%")& (df_same['GPA250']=="0%")& (df_same['GPA200']=="0%")& (df_same['GPA100']=="0%")& (df_same['GPA000']=="0%")].index)

In [41]:
df_same=df_same.drop(df_same[(df_same['GPA400']=="0.00%") & (df_same['GPA375']=="0.00%")& (df_same['GPA350']=="0.00%")& (df_same['GPA325']=="0.00%")& (df_same['GPA300']=="0.00%")& (df_same['GPA250']=="0.00%")& (df_same['GPA200']=="0.00%")& (df_same['GPA100']=="0.00%")& (df_same['GPA000']=="0.00%")].index)

In [47]:
df_same=df_same.drop(df_same[df_same['GPA400'].isnull()&df_same['GPA375'].isnull()&df_same['GPA350'].isnull()&df_same['GPA325'].isnull()&df_same['GPA300'].isnull()&df_same['GPA250'].isnull()&df_same['GPA200'].isnull()&df_same['GPA100'].isnull()&df_same['GPA000'].isnull()].index)

In [48]:
df_same

,postid,Name,ExtractName,Address,Year,GPA400,GPA375,GPA350,GPA325,GPA300,GPA250,GPA200,GPA100,GPA000
0,10011,American University,American University,"4400 Massachusetts Avenue, NW, Washington, Dis...",2023-2024,15%,25%,30%,20%,7%,2%,1%,0%,0%
4,10012,Clark University,Clark University,"950 Main Street, Worcester, Massachusetts, 016...",2023-2024,31%,24%,21%,13%,7%,4%,0%,0%,0%
5,10012,Clark University,Clark University,"950 Main Street, Worcester, MA 01610-1477",2021-2022,34%,26%,14%,11%,9%,6%,1%,NaN,NaN
6,10012,Clark University,Clark University,"950 Main Street, Worcester, MA 01610-1477",2018-2019,26%,53%,19%,2%,0%,0%,0%,0%,0%
12,10079,Dartmouth College,Dartmouth College,"16016 McNutt Hall, Hanover, NH 03755",2022-2023,94.5%,98.3%,99.8%,0.2%,0.2%,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,30073,Columbus State Community College,Columbus State Community College,"550 E Spring St, Columbus, OH 43215",2023-2024,10%,20%,30%,15%,10%,10%,3%,1%,1%
611,30073,Columbus State Community College,Columbus State Community College,"550 E Spring St, Columbus, OH 43215",2023-2024,15%,20%,25%,15%,10%,10%,3%,1%,1%
614,34270,Regent University,Regent University,"1000 Regent University Drive, Virginia Beach, ...",2022-2023,25.00,24.00,16.00,9.00,8.00,9.00,5.00,4.00,NaN
622,34274,Wayne State University,Wayne State University,"42 W. Warren Ave., Detroit, MI 48202",2021-2022,16.36%,20.33%,15.08%,14.95%,11.92%,16.49%,4.87%,NaN,NaN
623,34274,Wayne State University,Wayne State University,"42 W. Warren Ave., Detroit, MI. 48202",2020-2021,12.87%,19.34%,18.49%,14.99%,13.45%,16.74%,4.04%,0.07%,NaN