In [1]:
import pandas as pd

In [49]:
df=pd.read_csv("GPAs_part_1.csv")
df2=pd.read_csv("GPAs.csv")

In [53]:
df=pd.concat([df,df2])

In [54]:
df=df.drop(columns=['Unnamed: 0'])

In [56]:
df.reset_index(inplace=True)

In [57]:
df

,index,postid,Name,ExtractName,Address,Year,GPA400,GPA375,GPA350,GPA325,GPA300,GPA250,GPA200,GPA100,GPA000
0,0,10011,American University,American University,"4400 Massachusetts Avenue, NW, Washington, Dis...",2023-2024,15%,25%,30%,20%,7%,2%,1%,0%,0%
1,1,10011,American University,American University,"4400 Massachusetts Avenue, NW, Washington, D.C...",2021-2022,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%,0.00%
2,2,10011,American University,Western New England University,"1215 Wilbraham Road, Springfield, MA, 01119",2023-2024,36.43%,10.69%,12.66%,12.10%,11.11%,11.95%,4.92%,0.14%,0.00%
3,3,10011,American University,Loyola University Maryland,"4501 North Charles Street, Baltimore, MD, 2121...",2023-2024,33%,23%,21%,11%,6%,5%,1%,0%,0%
4,4,10012,Clark University,Clark University,"950 Main Street, Worcester, Massachusetts, 016...",2023-2024,31%,24%,21%,13%,7%,4%,0%,0%,0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1587,959,9935,University of Maryland-College Park,Bucknell University,"1 Dent Drive, Lewisburg, Pennsylvania, 17837, ...",2023-2024,8.45%,34.95%,29.61%,17.57%,7.86%,1.50%,0.10%,0.00%,0.00%
1588,960,9935,University of Maryland-College Park,University of New Hampshire,"3 Garrison Avenue, Durham, New Hampshire, 0382...",2023-2024,8,Percent who had GPA between 3.75 and 3.99,Percent who had GPA between 3.50 and 3.74,Percent who had GPA between 3.25 and 3.49,Percent who had GPA between 3.00 and 3.24,Percent who had GPA between 2.50 and 2.99,Percent who had GPA between 2.0 and 2.49,Percent who had GPA between 1.0 and 1.99,Percent who had GPA below 1.0
1589,961,9935,University of Maryland-College Park,Unknown University,Unknown Address,2023-2024,11.0%,39.0%,24.0%,17.0%,7.0%,2.0%,0.0%,0.0%,0.0%
1590,962,9936,Worcester Polytechnic Institute,Worcester Polytechnic Institute,"100 Institute Road, Worcester, MA 01609, USA",2023-2024,68.2%,17.1%,11.3%,2.3%,0.9%,0.2%,0%,0%,0%
1591,963,9936,Worcester Polytechnic Institute,Worcester Polytechnic Institute,"100 Institute Road, Worcester, MA 01609, USA",2022-2023,65%,16%,13%,4%,2%,0%,0%,0%,0%

In [58]:
df_same=df[df['Name']==df['ExtractName']]

In [59]:
df_same=df_same.drop(df_same[df_same['GPA400']=='0'].index)

In [60]:
df_same=df_same.drop(df_same[(df_same['GPA400']=="0%") & (df_same['GPA375']=="0%")& (df_same['GPA350']=="0%")& (df_same['GPA325']=="0%")& (df_same['GPA300']=="0%")& (df_same['GPA250']=="0%")& (df_same['GPA200']=="0%")& (df_same['GPA100']=="0%")& (df_same['GPA000']=="0%")].index)

In [61]:
df_same=df_same.drop(df_same[(df_same['GPA400']=="0.00%") & (df_same['GPA375']=="0.00%")& (df_same['GPA350']=="0.00%")& (df_same['GPA325']=="0.00%")& (df_same['GPA300']=="0.00%")& (df_same['GPA250']=="0.00%")& (df_same['GPA200']=="0.00%")& (df_same['GPA100']=="0.00%")& (df_same['GPA000']=="0.00%")].index)

In [62]:
df_same=df_same.drop(df_same[df_same['GPA400'].isnull()&df_same['GPA375'].isnull()&df_same['GPA350'].isnull()&df_same['GPA325'].isnull()&df_same['GPA300'].isnull()&df_same['GPA250'].isnull()&df_same['GPA200'].isnull()&df_same['GPA100'].isnull()&df_same['GPA000'].isnull()].index)

In [63]:
df_same

,index,postid,Name,ExtractName,Address,Year,GPA400,GPA375,GPA350,GPA325,GPA300,GPA250,GPA200,GPA100,GPA000
0,0,10011,American University,American University,"4400 Massachusetts Avenue, NW, Washington, Dis...",2023-2024,15%,25%,30%,20%,7%,2%,1%,0%,0%
4,4,10012,Clark University,Clark University,"950 Main Street, Worcester, Massachusetts, 016...",2023-2024,31%,24%,21%,13%,7%,4%,0%,0%,0%
5,5,10012,Clark University,Clark University,"950 Main Street, Worcester, MA 01610-1477",2021-2022,34%,26%,14%,11%,9%,6%,1%,NaN,NaN
6,6,10012,Clark University,Clark University,"950 Main Street, Worcester, MA 01610-1477",2018-2019,26%,53%,19%,2%,0%,0%,0%,0%,0%
12,12,10079,Dartmouth College,Dartmouth College,"16016 McNutt Hall, Hanover, NH 03755",2022-2023,94.5%,98.3%,99.8%,0.2%,0.2%,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1574,946,96915,Saint Mary's College,Saint Mary's College,"Notre Dame, Indiana, 46556",2023-2024,44.15%,25.54%,15.04%,9.79%,3.34%,2.14%,0.00%,0.00%,0.00%
1579,951,9780,University of Georgia,University of Georgia,"Administration Building, Athens, Georgia, 30602",2023-2024,81.87,15.56,1.76,0.33,0.20,0.20,0.08,0.00,0.00
1580,952,9780,University of Georgia,University of Georgia,"Administration Building, Athens, GA 30602",2022-2023,80.10%,16.46%,2.60%,0.32%,0.18%,0.27%,0.05%,0.02%,NaN
1590,962,9936,Worcester Polytechnic Institute,Worcester Polytechnic Institute,"100 Institute Road, Worcester, MA 01609, USA",2023-2024,68.2%,17.1%,11.3%,2.3%,0.9%,0.2%,0%,0%,0%
1591,963,9936,Worcester Polytechnic Institute,Worcester Polytechnic Institute,"100 Institute Road, Worcester, MA 01609, USA",2022-2023,65%,16%,13%,4%,2%,0%,0%,0%,0%

In [66]:
df_same=df_same.drop(df_same[df_same['GPA400'].apply(lambda x:len(str(x))>10)].index)

In [68]:
df_same.reset_index(drop=True,inplace=True)

In [91]:
df_same.to_csv("after.csv",index=False)